import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link style={{ color: "blue" }} href="/multiState">
        1. Learn to handle Multiple values in state in one usestate
      </Link>
      <br/>
      <Link href="/components/FormPage">
        Form
      </Link>
    </>
  );
}
